apiVersion: apps/v1
kind: Deployment
metadata:
  name: orra-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orra-dev
  template:
    metadata:
      labels:
        app: orra-dev
    spec:
      containers:
        - name: orra-dev
          image: sh21202/orra_dev:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: sr-orra-dev