apiVersion: v1
kind: Service
metadata:
  name: svc-orra-dev
spec:
  type: NodePort
  ports:
    - name: "8082"
      port: 8082
      targetPort: 80
      nodePort: 30002
  selector:
    app: orra-dev